version: '3.9'
services:

  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - 25432:5432
    env_file: pg.env

  people:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/people?createDatabaseIfNotExist=true
    depends_on:
      - postgres