name: People

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check for obsolet dependencies
        run: ./gradlew dependencyUpdate

      - name: Check style
        run: ./gradlew detekt

      - name: Analyze code
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: sonar

      - name: Build
        run: ./gradlew build




